#ifndef NOSTARAHAALIB_GLOBAL_H
#define NOSTARAHAALIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NOSTARAHAALIB_LIBRARY)
#  define NOSTARAHAALIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOSTARAHAALIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NOSTARAHAALIB_GLOBAL_H
