#ifndef DLLKORTINLUKU_GLOBAL_H
#define DLLKORTINLUKU_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLKORTINLUKU_LIBRARY)
#  define DLLKORTINLUKUSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLKORTINLUKUSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLKORTINLUKU_GLOBAL_H
