#ifndef MAKSALASKU_DLL_GLOBAL_H
#define MAKSALASKU_DLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAKSALASKU_DLL_LIBRARY)
#  define MAKSALASKU_DLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAKSALASKU_DLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKSALASKU_DLL_GLOBAL_H
