#ifndef DLLTILITAPAHTUMAT_GLOBAL_H
#define DLLTILITAPAHTUMAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLTILITAPAHTUMAT_LIBRARY)
#  define DLLTILITAPAHTUMATSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLTILITAPAHTUMATSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLTILITAPAHTUMAT_GLOBAL_H
